# -*- coding: utf-8 -*-
"""seoul_new.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ckvBLPu9BKAThuaQFBbzEmgAJYtMkTo4
"""

class SeoulPkg:
  def detail(self):
    print("[서울 도심 패키지] 호캉스 100만원")

if name == "main":
  print("seoul 모듈 직접 실행되었습니다.")
  trip_seoul = SeoulPkg()
  trip_seoul.detail()
else:
  print("외부에서 seoul 모듈 실행되었습니다.")