# -*- coding: utf-8 -*-
"""theater_module_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rX8NnjP85vaYCiveUPUek_zlYH9rwrAZ
"""

def price(people):
  print(f"영화표 가격은 {people * 10000} 입니다.")

def price_student(people):
  print(f"영화표 가격은 {people * 10000 * 0.2} 입니다.")

def price_vip(people):
  print(f"영화표 가격은 {people * 15000} 입니다.")